class indentityRunner{

	public static void main(String[] person)
	{
		
		String Name1="Hareesh Bewoor"; 
		String Name2="Shubham Garve";
		String Name3="Akshay";
		String Name4="Hareesha H R";
		String Name5="Suraj S";
		String Name6="Sandeep s sonnad";
		String Name7="Karthik. N";
		String Name8="chidanand s patroti";
		String Name9="Rohan R P";
		String Name10="Anil Kumar D";
		String Name11="Hithesh kumar";
		String Name12="Prasad M";
		
		String Email1="hareeshahb.xworkz@gmail.com";
		String Email2="shugarve.xworkz@gmail.com";
		String Email3="akshayj.xworkz@gmail.com";
		String Email4="hareeshahr.xworkz@gmail.com";
		String Email5="surajs.xworkz@gmail.com";
		String Email6="sandeepssonnadxworks@gmail.com";
		String Email7="karthikn.xworkz@gmail.com";
		String Email8="chidanandxworkz@gmail.com";
		String Email9="rohanp.xworkz@gmail.com";
		String Email10="anil.xworkz@gmail.com";
		String Email11="hithesh.xworkz@gmail.com";
		String Email12="prasadm.xworkz@gmail.com";
		
		Long Mobile1=6364535754L;
		Long Mobile2=8767938302L;
		Long Mobile3=9900238734L;
		Long Mobile4=9900775088L;
		Long Mobile5=7259303408L;
		Long Mobile6=9741426746L;
		Long Mobile7=6362060352L;
		Long Mobile8=8310437144L;
		Long Mobile9=8088245073L;
		Long Mobile10=9380894119L;
		Long Mobile11=9535044021L;
		Long Mobile12=7795310346L;
		
		String Address1="Bangalore";
		String Address2="Chikkaballapur";
		String Address3="Chitradurga";
		String Address4="Davanagere";
		String Address5="Kolar";
		String Address6="Ramanagara";
		String Address7="Shimoga";
		String Address8="Tumkur";
		String Address9="Bellary";
		String Address10="Bidar";
		String Address11="Kalabuargi";
		String Address12="Koppal";
		String Address13="Raichur";
		
		int Age1=21;
		int Age2=22;
		int Age3=23;
		int Age4=20;
		int Age5=19;
		int Age6=22;
		int Age7=23;
		int Age8=21;
		int Age9=24;
		int Age10=20;
		int Age11=20;
		int Age12=18;
		
		String Gender1="male";
		String Gender2="male";
		String Gender3="male";
		String Gender4="female";
		String Gender5="female";
		String Gender6="female";
		String Gender7="female";
		String Gender8="male";
		String Gender9="female";
		String Gender10="male";
		String Gender11="male";
		String Gender12="female";
		
		Boolean working1=true;
		Boolean working2=true;
		Boolean working3=true;
		Boolean working4=true;
		Boolean working5=false;
		Boolean working6=false;
		Boolean working7=false;
		Boolean working8=true;
		Boolean working9=false;
		Boolean working10=true;
		Boolean working11=true;
		Boolean working12=false;
		
		int Shirtsize1=36;
		int Shirtsize2=38;
		int Shirtsize3=34;
		int Shirtsize4=42;
		int Shirtsize5=44;
		int Shirtsize6=38;
		int Shirtsize7=32;
		int Shirtsize8=34;
		int Shirtsize9=36;
		int Shirtsize10=36;
		int Shirtsize11=38;
		int Shirtsize12=46;
		
		int Pantsize1=38;
		int Pantsize2=40;
		int Pantsize3=36;
		int Pantsize4=28;
		int Pantsize5=30;
		int Pantsize6=32;
		int Pantsize7=30;
		int Pantsize8=38;
		int Pantsize9=36;
		int Pantsize10=38;
		int Pantsize11=40;
		int Pantsize12=32;
		
		int weight1=65;
		int weight2=75;
		int weight3=58;
		int weight4=69;
		int weight5=72;
		int weight6=87;
		int weight7=95;
		int weight8=52;
		int weight9=64;
		int weight10=59;
		int weight11=60;
		int weight12=79;
		
		String height1="5ft 9in";
		String height2="5ft 8in";
		String height3="4ft 9in";
		String height4="5ft 11in";
		String height5="6ft 1in";
		String height6="4ft 10in";
		String height7="4ft 8in";
		String height8="5ft 11in";
		String height9="4ft 5in";
		String height10="5ft 9in";
		String height11="5ft 0in";
		String height12="5ft 2in";
		
	System.out.println("***************************************************");	
		ArgumentMethod.NameAndEmail(Name1,Email1);
		ArgumentMethod.NameAndEmail(Name2,Email2);
		ArgumentMethod.NameAndEmail(Name3,Email3);
		ArgumentMethod.NameAndEmail(Name4,Email4);
		ArgumentMethod.NameAndEmail(Name5,Email5);
		ArgumentMethod.NameAndEmail(Name6,Email6);
		ArgumentMethod.NameAndEmail(Name7,Email7);
		ArgumentMethod.NameAndEmail(Name8,Email8);
		ArgumentMethod.NameAndEmail(Name9,Email9);
		ArgumentMethod.NameAndEmail(Name10,Email10);
		ArgumentMethod.NameAndEmail(Name11,Email11);
		ArgumentMethod.NameAndEmail(Name12,Email12);
		ArgumentMethod.NameAndEmail("Vinay H P","vinayhp.xworkz@gmail.com");

		
	System.out.println("***************************************************");
		ArgumentMethod.NameAndMobile(Name1,Mobile1);
		ArgumentMethod.NameAndMobile(Name2,Mobile2);
		ArgumentMethod.NameAndMobile(Name3,Mobile3);
		ArgumentMethod.NameAndMobile(Name4,Mobile4);
		ArgumentMethod.NameAndMobile(Name5,Mobile5);
		ArgumentMethod.NameAndMobile(Name6,Mobile6);
		ArgumentMethod.NameAndMobile(Name7,Mobile7);
		ArgumentMethod.NameAndMobile(Name8,Mobile8);
		ArgumentMethod.NameAndMobile(Name9,Mobile9);
		ArgumentMethod.NameAndMobile(Name10,Mobile10);
		ArgumentMethod.NameAndMobile(Name11,Mobile11);
		ArgumentMethod.NameAndMobile(Name12,Mobile12);
		ArgumentMethod.NameAndMobile(Name12,Mobile12);
		ArgumentMethod.NameAndMobile("Ashok Kumar",8197533763L);
	System.out.println("***************************************************");	
		ArgumentMethod.NameAndAge(Name1,Age1);
		ArgumentMethod.NameAndAge(Name2,Age2);
		ArgumentMethod.NameAndAge(Name3,Age3);
		ArgumentMethod.NameAndAge(Name4,Age4);
		ArgumentMethod.NameAndAge(Name5,Age5);
		ArgumentMethod.NameAndAge(Name6,Age6);
		ArgumentMethod.NameAndAge(Name7,Age7);
		ArgumentMethod.NameAndAge(Name8,Age8);
		ArgumentMethod.NameAndAge(Name9,Age9);
		ArgumentMethod.NameAndAge(Name10,Age10);
		ArgumentMethod.NameAndAge(Name11,Age11);
		ArgumentMethod.NameAndAge(Name12,Age12);
		ArgumentMethod.NameAndAge("Chetan S V",24);
	System.out.println("***************************************************");
		ArgumentMethod.NameAndAddress(Name1,Address1);
		ArgumentMethod.NameAndAddress(Name2,Address2);
		ArgumentMethod.NameAndAddress(Name3,Address3);
		ArgumentMethod.NameAndAddress(Name4,Address4);
		ArgumentMethod.NameAndAddress(Name5,Address5);
		ArgumentMethod.NameAndAddress(Name6,Address6);
		ArgumentMethod.NameAndAddress(Name7,Address7);
		ArgumentMethod.NameAndAddress(Name8,Address8);
		ArgumentMethod.NameAndAddress(Name9,Address9);
		ArgumentMethod.NameAndAddress(Name10,Address10);
		ArgumentMethod.NameAndAddress(Name11,Address11);
		ArgumentMethod.NameAndAddress(Name12,Address12);
		ArgumentMethod.NameAndAddress("shivalingesh k","Banglore");
	System.out.println("***************************************************");
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name1,Email1,Address1,Age1);
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name2,Email2,Address2,Age2);
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name3,Email3,Address3,Age3);
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name4,Email4,Address4,Age4);
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name5,Email5,Address5,Age5);
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name6,Email6,Address6,Age6);
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name7,Email7,Address7,Age7);
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name8,Email8,Address8,Age8);
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name9,Email9,Address9,Age9);
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name10,Email10,Address10,Age10);
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name11,Email11,Address11,Age11);
		ArgumentMethod.NameAndEmailAndAddressAndAge(Name12,Email12,Address12,Age12);
		ArgumentMethod.NameAndEmailAndAddressAndAge("Manu S P","manu. xworkz@gmail.com ","davangere",28);
	System.out.println("***************************************************");
		ArgumentMethod.NameAndGender(Name1,Gender1);
		ArgumentMethod.NameAndGender(Name2,Gender2);
		ArgumentMethod.NameAndGender(Name3,Gender3);
		ArgumentMethod.NameAndGender(Name4,Gender4);
		ArgumentMethod.NameAndGender(Name5,Gender5);
		ArgumentMethod.NameAndGender(Name6,Gender6);
		ArgumentMethod.NameAndGender(Name7,Gender7);
		ArgumentMethod.NameAndGender(Name8,Gender8);
		ArgumentMethod.NameAndGender(Name9,Gender9);
		ArgumentMethod.NameAndGender(Name10,Gender10);
		ArgumentMethod.NameAndGender(Name11,Gender11);
		ArgumentMethod.NameAndGender(Name12,Gender12);
		ArgumentMethod.NameAndGender("Niranjan C M","male");
	System.out.println("***************************************************");
		ArgumentMethod.NameAndWorking(Name1,working1);
		ArgumentMethod.NameAndWorking(Name2,working2);
		ArgumentMethod.NameAndWorking(Name3,working3);
		ArgumentMethod.NameAndWorking(Name4,working4);
		ArgumentMethod.NameAndWorking(Name5,working5);
		ArgumentMethod.NameAndWorking(Name6,working6);
		ArgumentMethod.NameAndWorking(Name7,working7);
		ArgumentMethod.NameAndWorking(Name8,working8);
		ArgumentMethod.NameAndWorking(Name9,working9);
		ArgumentMethod.NameAndWorking(Name10,working10);
		ArgumentMethod.NameAndWorking(Name11,working11);
		ArgumentMethod.NameAndWorking(Name12,working12);
		ArgumentMethod.NameAndWorking("Tilak Gowda H K",true);
	System.out.println("***************************************************");
		ArgumentMethod.NameAndShirtSize(Name1,Shirtsize1);
		ArgumentMethod.NameAndShirtSize(Name2,Shirtsize2);
		ArgumentMethod.NameAndShirtSize(Name3,Shirtsize3);
		ArgumentMethod.NameAndShirtSize(Name4,Shirtsize4);
		ArgumentMethod.NameAndShirtSize(Name5,Shirtsize5);
		ArgumentMethod.NameAndShirtSize(Name6,Shirtsize6);
		ArgumentMethod.NameAndShirtSize(Name7,Shirtsize7);
		ArgumentMethod.NameAndShirtSize(Name8,Shirtsize8);
		ArgumentMethod.NameAndShirtSize(Name9,Shirtsize9);
		ArgumentMethod.NameAndShirtSize(Name10,Shirtsize10);
		ArgumentMethod.NameAndShirtSize(Name11,Shirtsize11);
		ArgumentMethod.NameAndShirtSize(Name12,Shirtsize12);
		ArgumentMethod.NameAndShirtSize("Hanamant S S",38);
	System.out.println("***************************************************");
		ArgumentMethod.NameAndPantSize(Name1,Pantsize1);
		ArgumentMethod.NameAndPantSize(Name2,Pantsize2);
		ArgumentMethod.NameAndPantSize(Name3,Pantsize3);
		ArgumentMethod.NameAndPantSize(Name4,Pantsize4);
		ArgumentMethod.NameAndPantSize(Name5,Pantsize5);
		ArgumentMethod.NameAndPantSize(Name6,Pantsize6);
		ArgumentMethod.NameAndPantSize(Name7,Pantsize7);
		ArgumentMethod.NameAndPantSize(Name8,Pantsize8);
		ArgumentMethod.NameAndPantSize(Name9,Pantsize9);
		ArgumentMethod.NameAndPantSize(Name10,Pantsize10);
		ArgumentMethod.NameAndPantSize(Name11,Pantsize11);
		ArgumentMethod.NameAndPantSize(Name12,Pantsize12);
		ArgumentMethod.NameAndPantSize("Niranjan C M",38);

	System.out.println("***************************************************");
		ArgumentMethod.NameAndWeightAndHeight(Name1,weight1,height1);
		ArgumentMethod.NameAndWeightAndHeight(Name2,weight2,height2);
		ArgumentMethod.NameAndWeightAndHeight(Name3,weight3,height3);
		ArgumentMethod.NameAndWeightAndHeight(Name4,weight4,height4);
		ArgumentMethod.NameAndWeightAndHeight(Name5,weight5,height5);
		ArgumentMethod.NameAndWeightAndHeight(Name6,weight6,height6);
		ArgumentMethod.NameAndWeightAndHeight(Name7,weight7,height7);
		ArgumentMethod.NameAndWeightAndHeight(Name8,weight8,height8);
		ArgumentMethod.NameAndWeightAndHeight(Name9,weight9,height9);
		ArgumentMethod.NameAndWeightAndHeight(Name10,weight10,height10);
		ArgumentMethod.NameAndWeightAndHeight(Name11,weight11,height11);
		ArgumentMethod.NameAndWeightAndHeight(Name12,weight12,height12);
		ArgumentMethod.NameAndWeightAndHeight("Vinay H P",88,"5ft 9in");
	System.out.println("***************************************************");
	}

}